CREATE DATABASE bdtienda;

CREATE TABLE USUARIO(
    ID int(11) NOT NULL AUTO_INCREMENT,
    NAME varchar(120) DEFAULT NULL,
    USER VARCHAR(120) DEFAULT NULL,
    PASSWORD VARCHAR(120) DEFAULT NULL,
    ROL VARCHAR(120) DEFAULT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT CKC_ROL CHECK(ROL='ADMIN' OR ROL='NO-ADMIN')
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;

INSERT INTO usuario VALUES(NULL,'Luz','ldante','09lucas.','ADMIN');
INSERT INTO usuario VALUES(NULL,'Camilo','cperafan','cris99','NO-ADMIN');
INSERT INTO usuario VALUES(NULL,'Eliana','eacamayo','joseM28.','NO-ADMIN');


CREATE TABLE PRODUCTO(
    COD INT(11) NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(120) DEFAULT NULL,
    PRICE INT(15) NOT NULL,
    IMAGE LONGBLOB,
    PRIMARY KEY(COD)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


CREATE TABLE CARROCOMPRA(
    ID INT(11) NOT NULL,
    COD INT(11) NOT NULL,
    FECHA DATE,
    FOREIGN KEY (ID) REFERENCES USUARIO(ID),
    FOREIGN KEY (COD) REFERENCES PRODUCTO(COD)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
